// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtxsmokvmqiwcszqzunh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0eHNtb2t2bXFpd2NzenF6dW5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NDI5MzIsImV4cCI6MjA2MjIxODkzMn0.mmI-4OaCHPxungV0hDg04qhoqkarC4qB-PYspcJx5G8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);